# 模糊抓取订阅链接-订阅链接（webfuzz类似二选一）
- type: webfuzzsub
  options:
    url: http://ss.openwert.icu/
- type: webfuzzsub
  options:
    url: https://raw.githubusercontent.com/du5/free/master/sub.list
- type: webfuzzsub
  options:
    url: https://www.butnono.com/latest-2020-freevpn-v2ray-ss-ssr-address.html
- type: webfuzzsub
  options:
    url: https://merlinblog.xyz/wiki/freess.html
- type: webfuzzsub
  options:
    url: https://raw.githubusercontent.com/du5/free/master/sub.list
- type: webfuzzsub
  options:
    url: http://luo.openwert.icu/
- type: webfuzzsub
  options:
    url: https://raw.githubusercontent.com/ssrsub/ssr/master/Surge.conf
- type: webfuzzsub
  options:
    url: https://github.com/Alvin9999/new-pac/wiki/ss%E5%85%8D%E8%B4%B9%E8%B4%A6%E5%8F%B7
- type: webfuzzsub
  options:
    url: https://github.com/colatiger/v2ray-nodes
- type: webfuzzsub
  options:
    url: https://docs.google.com/document/d/1x3b07u_AjVq137WIaiJDN_TbXP48NCSb9UQE8Ag1vVA/edit
- type: webfuzzsub
  options:
    url: https://merlinblog.xyz/wiki/freess.html
- type: webfuzz
  options:
    url: https://merlinblog.xyz/wiki/freess.html
- type: webfuzz
  options:
    url: https://itlao5.com/wp/7034.html
- type: webfuzz
  options:
    url: https://github.com/Alvin9999/new-pac/wiki/ss%E5%85%8D%E8%B4%B9%E8%B4%A6%E5%8F%B7
- type: webfuzz
  options:
    url: https://baiyunju.cc/7119
- type: webfuzz
  options:
    url: https://github.com/freefq/free
- type: webfuzz
  options:
    url: https://zfjvpn.gitbook.io/123/
- type: webfuzz
  options:
    url: https://t.me/s/SSRlist?before=1378
- type: webfuzz
  options:
    url: https://github.com/zmike1993/hello-world/wiki/SSR%E5%85%8D%E8%B4%B9%E8%8A%82%E7%82%B9%EF%BC%88%E5%AE%9E%E6%97%B6%E6%9B%B4%E6%96%B0%EF%BC%89
- type: webfuzz
  options:
    url: https://github-wiki-see.page/m/zmike1993/hello-world/wiki/SSR%E5%85%8D%E8%B4%B9%E8%8A%82%E7%82%B9%EF%BC%88%E5%AE%9E%E6%97%B6%E6%9B%B4%E6%96%B0%EF%BC%89
- type: webfuzz
  options:
    url: http://luo.openwert.icu/
- type: webfuzzsub
  options:
    url: 
- type: webfuzzsub
  options:
    url: 
- type: webfuzzsub
  options:
    url: 
- type: webfuzzsub
  options:
    url: 
- type: webfuzzsub
  options:
    url: 
- type: webfuzzsub
  options:
    url: 

# clash格式订阅链接
- type: clash
  options:
    url: https://github.com/aiboboxx/clashfree
- type: clash
  options:
    url: https://sub.xeton.dev/sub?target=clash&new_name=true&url=https%3A%2F%2Fraw.githubusercontent.com%2Faiboboxx%2Fv2rayfree%2Fmain%2Fv2&insert=false&config=https%3A%2F%2Fraw.githubusercontent.com%2FACL4SSR%2FACL4SSR%2Fmaster%2FClash%2Fconfig%2FACL4SSR_Online.ini&emoji=true&list=false&tfo=false&scv=false&fdn=false&sort=false
- type: clash
  options:
    url: 
- type: clash
  options:
    url: 
- type: clash
  options:
    url: 
- type: clash
  options:
    url: 
- type: clash
  options:
    url: 
# 订阅链接-b64编码
- type: subscribe
  options:
    url: https://raw.githubusercontent.com/ssrsub/ssr/master/v2ray
- type: subscribe
  options:
    url: https://raw.githubusercontent.com/aiboboxx/v2rayfree/main/v2
- type: subscribe
  options:
    url: https://raw.githubusercontent.com/ssrsub/ssr/master/ssrsub
- type: subscribe
  options:
    url: https://github.com/learnhard-cn/free_proxy_ss/blob/main/ss/sssub
- type: subscribe
  options:
    url: https://github.com/learnhard-cn/free_proxy_ss/blob/main/v2ray/v2raysub
- type: subscribe
  options:
    url: https://v2b.xiaoqikeji.tk/api/v1/client/subscribe?token=bf13f4b95f2f147bb346648dd20aba03
- type: subscribe
  options:
    url: https://raw.githubusercontent.com/alanbobs999/TopFreeProxies/master/Eternity
- type: subscribe
  options:
    url: https://raw.githubusercontent.com/ssrsub/ssr/master/ss-sub
- type: subscribe
  options:
    url: https://raw.githubusercontent.com/freefq/free/master/ssr
- type: subscribe
  options:
    url: https://raw.githubusercontent.com/freefq/free/master/v2
- type: subscribe
  options:
    url: 
- type: subscribe
  options:
    url: 
- type: subscribe
  options:
    url: 
- type: subscribe
  options:
    url: 
- type: subscribe
  options:
    url: 
- type: subscribe
  options:
    url: 

# tg频道抓取
- type: tgchannel
  options:
    channel: MTProtoSS
    num: 200
- type: tgchannel
  options:
    channel: hkaa0
    num: 200
- type: tgchannel
  options:
    channel: v2rayN_admin_cn
    num: 200
- type: tgchannel
  options:
    channel: v2rayNssr
    num: 200
- type: tgchannel
  options:
    channel: ssrList
    num: 200
- type: tgchannel
  options:
    channel: gongyijichangfenxiang
    num: 200
- type: tgchannel
  options:
    channel: GY_mtproto
    num: 200
- type: tgchannel
  options:
    channel: SSRCOM
    num: 200
- type: tgchannel
  options:
    channel: 
    num: 200
# 翻墙党论坛抓取-静态网页
- type: web-fanqiangdang
  options:
    url: https://fanqiangdang.com/forum-48-1.html
- type: web-fanqiangdang
  options:
    url: http://vps90.com/vps/2941.html
- type: web-fanqiangdang
  options:
    url: https://xtrojan.org/free-ss-shadowsocks
- type: web-fanqiangdang
  options:
    url: https://v2cross.com/archives/1884
- type: web-fanqiangdang
  options:
    url: https://old.iyio.net/2022/04/1602.html
- type: web-fanqiangdang
  options:
    url: https://www.cfmem.com/2022/07/20220714-2022504k-v2rayclash-vpn.html
- type: web-fanqiangdang
  options:
    url: http://vps90.com/vps/2824.html
- type: web-fanqiangdang
  options:
    url: https://www.lmlphp.com/user/356980/article/item/8196734/
- type: web-fanqiangdang
  options:
    url: https://github.com/FairyWorld/fq_v2rayfree
- type: web-fanqiangdang
  options:
    url: https://xtrojan.org/free-ss-shadowsocks
- type: web-fanqiangdang
  options:
    url: https://github.com/monsterCCH/freefq
- type: web-fanqiangdang
  options:
    url: 
- type: web-fanqiangdang
  options:
    url: 
- type: web-fanqiangdang
  options:
    url: 
- type: web-fanqiangdang
  options:
    url: 
- type: web-fanqiangdang
  options:
    url: 
- type: web-fanqiangdang
  options:
    url: 
# 网页模糊抓取
- type: webfuzz
  options:
    url: 
# 某个网站抓取
- type: web-freessrxyz
  options:
